
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_Dialog(object):
    def guardar(self):
        direccion= self.calle.text()+", "+self.cp.text()+", "+self.ciudad.text()+", "+self.pais.text()
        nuevoContacto=[(self.nombre.text(),direccion,self.contacto.text(),self.telefono.text(),self.correo.text(),float(self.iva.text()))]
        self.cur.execute("insert into contactos values (?,?,?,?,?,?)",nuevoContacto[0])
        self.con.commit()
        self.con.close()
        from elegirCon import Ui_Dialog
        self.window= QtWidgets.QDialog()
        self.ui= Ui_Dialog()
        self.ui.setupUi(self.window, self.name, True)
        self.window.show()
        self.ui.listContactos.clicked.connect(self.window.close)
    def setupUi(self, Dialog,nombre, contacto):
        Dialog.setObjectName("Dialog")
        Dialog.resize(506, 512)
        self.name= nombre
        self.con= sqlite3.connect("BaseDeDatos"+self.name)
        self.cur= self.con.cursor()
        self.cur.execute("select * from contactos where nombre=?", (str(contacto[0]), ))
        contacto= self.cur.fetchone()
        self.direccion= contacto[1].split(", ")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nombre = QtWidgets.QLineEdit(Dialog)
        self.nombre.setGeometry(QtCore.QRect(130, 70, 231, 20))
        self.nombre.setObjectName("nombre")
        self.nombre.setText(contacto[0])
        self.pais = QtWidgets.QLineEdit(Dialog)
        self.pais.setGeometry(QtCore.QRect(130, 110, 231, 20))
        self.pais.setObjectName("pais")
        self.pais.setText(self.direccion[4])
        self.ciudad = QtWidgets.QLineEdit(Dialog)
        self.ciudad.setGeometry(QtCore.QRect(130, 150, 231, 20))
        self.ciudad.setObjectName("ciudad")
        self.ciudad.setText(self.direccion[3])
        self.cp = QtWidgets.QLineEdit(Dialog)
        self.cp.setGeometry(QtCore.QRect(130, 190, 231, 20))
        self.cp.setObjectName("cp")
        self.cp.setText(self.direccion[2])
        self.calle = QtWidgets.QLineEdit(Dialog)
        self.calle.setGeometry(QtCore.QRect(130, 230, 231, 20))
        self.calle.setObjectName("calle")
        self.calle.setText(self.direccion[0]+", "+self.direccion[1])
        self.contacto = QtWidgets.QLineEdit(Dialog)
        self.contacto.setGeometry(QtCore.QRect(130, 270, 231, 20))
        self.contacto.setObjectName("contacto")
        self.contacto.setText(contacto[2])
        self.telefono = QtWidgets.QLineEdit(Dialog)
        self.telefono.setGeometry(QtCore.QRect(130, 310, 231, 20))
        self.telefono.setObjectName("telefono")
        self.telefono.setText(contacto[3])
        self.correo = QtWidgets.QLineEdit(Dialog)
        self.correo.setGeometry(QtCore.QRect(130, 350, 231, 20))
        self.correo.setObjectName("correo")
        self.correo.setText(contacto[4])
        self.iva = QtWidgets.QLineEdit(Dialog)
        self.iva.setGeometry(QtCore.QRect(130, 390, 231, 20))
        self.iva.setObjectName("iva")
        self.iva.setText(str(contacto[5]))
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 270, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 310, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 350, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 390, 47, 13))
        self.label_10.setObjectName("label_10")
        self.buttonGuardar = QtWidgets.QPushButton(Dialog)
        self.buttonGuardar.setGeometry(QtCore.QRect(190, 440, 75, 23))
        self.buttonGuardar.setObjectName("buttonGuardar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Editar contacto"))
        self.label_2.setText(_translate("Dialog", "Nombre"))
        self.label_3.setText(_translate("Dialog", "País"))
        self.label_4.setText(_translate("Dialog", "Ciudad"))
        self.label_5.setText(_translate("Dialog", "CP"))
        self.label_6.setText(_translate("Dialog", "Calle"))
        self.label_7.setText(_translate("Dialog", "Contacto"))
        self.label_8.setText(_translate("Dialog", "Teléfono"))
        self.label_9.setText(_translate("Dialog", "Correo"))
        self.label_10.setText(_translate("Dialog", "IVA"))
        self.buttonGuardar.setText(_translate("Dialog", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
