
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def abrirContactos(self,nombre):
        from elegirCon import Ui_Dialog
        self.window= QtWidgets.QDialog()
        self.ui= Ui_Dialog()
        self.ui.setupUi(self.window,nombre,True)
        self.window.show()
        self.ui.listContactos.clicked.connect(self.window.close)
    def abrirPipeline(self, nombre):
        from pipeline import Ui_Pipeline
        self.window= QtWidgets.QMainWindow()
        self.ui= Ui_Pipeline()
        self.ui.setupUi(self.window,nombre)
        self.window.show()
        self.ui.buttonAtras.clicked.connect(self.window.close)
        self.ui.buttonNuevo.clicked.connect(self.window.close)
        self.ui.listCalificado.clicked.connect(self.window.close)
        self.ui.listGanado.clicked.connect(self.window.close)
        self.ui.listNuevo.clicked.connect(self.window.close)
        self.ui.listPropuesta.clicked.connect(self.window.close)
    def salir(self):
        from window import Ui_Login
        self.window= QtWidgets.QDialog()
        self.ui= Ui_Login()
        self.ui.setupUi(self.window)
        self.window.show()
        self.ui.registro.clicked.connect(self.window.close)
        self.ui.entrar.clicked.connect(self.window.close)
    def setupUi(self, MainWindow,nombre):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.oportunidadesButton = QtWidgets.QPushButton(MainWindow, clicked= lambda: self.abrirPipeline(nombre))
        self.oportunidadesButton.setGeometry(QtCore.QRect(100, 100, 91, 81))
        self.oportunidadesButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("oportunidades.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oportunidadesButton.setIcon(icon)
        self.oportunidadesButton.setIconSize(QtCore.QSize(91, 81))
        self.oportunidadesButton.setObjectName("oportunidadesButton")
        self.contactosButton = QtWidgets.QPushButton(MainWindow, clicked=lambda:self.abrirContactos(nombre))
        self.contactosButton.setGeometry(QtCore.QRect(320, 100, 91, 81))
        self.contactosButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("contactos2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactosButton.setIcon(icon1)
        self.contactosButton.setIconSize(QtCore.QSize(89, 75))
        self.contactosButton.setObjectName("contactosButton")
        self.presupuestosButton = QtWidgets.QPushButton(self.centralwidget)
        self.presupuestosButton.setGeometry(QtCore.QRect(540, 100, 91, 81))
        self.presupuestosButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("presupuestos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.presupuestosButton.setIcon(icon2)
        self.presupuestosButton.setIconSize(QtCore.QSize(91, 81))
        self.presupuestosButton.setObjectName("presupuestosButton")
        self.pedidosButton = QtWidgets.QPushButton(self.centralwidget)
        self.pedidosButton.setGeometry(QtCore.QRect(100, 300, 91, 81))
        self.pedidosButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pedidos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pedidosButton.setIcon(icon3)
        self.pedidosButton.setIconSize(QtCore.QSize(91, 81))
        self.pedidosButton.setObjectName("pedidosButton")
        self.inventarioButton = QtWidgets.QPushButton(self.centralwidget)
        self.inventarioButton.setGeometry(QtCore.QRect(320, 300, 91, 81))
        self.inventarioButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("inventario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inventarioButton.setIcon(icon4)
        self.inventarioButton.setIconSize(QtCore.QSize(91, 81))
        self.inventarioButton.setObjectName("inventarioButton")
        self.salidaButton = QtWidgets.QPushButton(MainWindow, clicked=lambda:self.salir())
        self.salidaButton.setGeometry(QtCore.QRect(540, 300, 91, 81))
        self.salidaButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("salida.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.salidaButton.setIcon(icon5)
        self.salidaButton.setIconSize(QtCore.QSize(91, 81))
        self.salidaButton.setObjectName("salidaButton")
        self.labelOportunidades = QtWidgets.QLabel(self.centralwidget)
        self.labelOportunidades.setGeometry(QtCore.QRect(90, 200, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(True)
        font.setWeight(75)
        self.labelOportunidades.setFont(font)
        self.labelOportunidades.setObjectName("labelOportunidades")
        self.labelContactos = QtWidgets.QLabel(self.centralwidget)
        self.labelContactos.setGeometry(QtCore.QRect(325, 200, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(True)
        font.setWeight(75)
        self.labelContactos.setFont(font)
        self.labelContactos.setObjectName("labelContactos")
        self.labelPresupuestos = QtWidgets.QLabel(self.centralwidget)
        self.labelPresupuestos.setGeometry(QtCore.QRect(530, 200, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(True)
        font.setWeight(75)
        self.labelPresupuestos.setFont(font)
        self.labelPresupuestos.setObjectName("labelPresupuestos")
        self.labelPedidos = QtWidgets.QLabel(self.centralwidget)
        self.labelPedidos.setGeometry(QtCore.QRect(120, 400, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(True)
        font.setWeight(75)
        self.labelPedidos.setFont(font)
        self.labelPedidos.setObjectName("labelPedidos")
        self.labelInventario = QtWidgets.QLabel(self.centralwidget)
        self.labelInventario.setGeometry(QtCore.QRect(320, 400, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(True)
        font.setWeight(75)
        self.labelInventario.setFont(font)
        self.labelInventario.setObjectName("labelInventario")
        self.labelSalir = QtWidgets.QLabel(self.centralwidget)
        self.labelSalir.setGeometry(QtCore.QRect(560, 400, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(True)
        font.setWeight(75)
        self.labelSalir.setFont(font)
        self.labelSalir.setObjectName("labelSalir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 21))
        self.menubar.setObjectName("menubar")
        self.menuCuenta = QtWidgets.QMenu(self.menubar)
        self.menuCuenta.setObjectName("menuCuenta")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEditar = QtWidgets.QAction(MainWindow)
        self.actionEditar.setObjectName("actionEditar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSalir.triggered.connect(self.salir)
        self.menuCuenta.addAction(self.actionEditar)
        self.menuCuenta.addAction(self.actionSalir)
        self.menubar.addAction(self.menuCuenta.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelOportunidades.setText(_translate("MainWindow", "Oportunidades"))
        self.labelContactos.setText(_translate("MainWindow", "Contactos"))
        self.labelPresupuestos.setText(_translate("MainWindow", "Presupuestos"))
        self.labelPedidos.setText(_translate("MainWindow", "Pedidos"))
        self.labelInventario.setText(_translate("MainWindow", "Inventario"))
        self.labelSalir.setText(_translate("MainWindow", "Salir"))
        self.menuCuenta.setTitle(_translate("MainWindow", "Cuenta"))
        self.actionEditar.setText(_translate("MainWindow", "Editar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
