import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_Dialog(object):
    def abrirPipeline(self, nombre):
        from pipeline import Ui_Pipeline
        self.window= QtWidgets.QMainWindow()
        self.ui= Ui_Pipeline()
        self.ui.setupUi(self.window, nombre)
        self.window.show()
        self.ui.buttonAtras.clicked.connect(self.window.close)
        self.ui.buttonNuevo.clicked.connect(self.window.close)
    def agregar(self, nombre, oportunidad, contacto, ingreso,correo, telefono, tipo):
        try:
            datos=[(contacto, oportunidad, correo, telefono, ingreso, tipo)]
            empresa= "BaseDeDatos"+nombre
            con= sqlite3.connect(empresa)
            cur = con.cursor()
            cur.execute("insert into oportunidades values(?,?,?,?,?,?)", (str(contacto),str(oportunidad),str(correo),str(telefono),float(ingreso),str(tipo)))
            msgBox = QMessageBox()
            msgBox.setText("La oportunidad ha sido agregada con éxito")
            msgBox.setWindowTitle("Information")
            msgBox.setIcon(QMessageBox.Information)
            msgBox.exec()
            con.commit()
            con.close()
            self.abrirPipeline(nombre)
        except Exception as a:
            print(a);
    def setupUi(self, Dialog, nombre):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 401)
        self.oportunidad = QtWidgets.QLineEdit(Dialog)
        self.oportunidad.setGeometry(QtCore.QRect(130, 70, 201, 20))
        self.oportunidad.setObjectName("oportunidad")
        self.contacto = QtWidgets.QLineEdit(Dialog)
        self.contacto.setGeometry(QtCore.QRect(130, 110, 201, 20))
        self.contacto.setObjectName("contacto")
        self.ingresoEsperado = QtWidgets.QLineEdit(Dialog)
        self.ingresoEsperado.setGeometry(QtCore.QRect(130, 150, 201, 20))
        self.ingresoEsperado.setObjectName("ingresoEsperado")
        self.correo = QtWidgets.QLineEdit(Dialog)
        self.correo.setGeometry(QtCore.QRect(130, 190, 201, 20))
        self.correo.setObjectName("correo")
        self.telefono = QtWidgets.QLineEdit(Dialog)
        self.telefono.setGeometry(QtCore.QRect(130, 230, 201, 20))
        self.telefono.setObjectName("telefono")
        self.tipo = QtWidgets.QLineEdit(Dialog)
        self.tipo.setGeometry(QtCore.QRect(130, 270, 201, 20))
        self.tipo.setObjectName("tipo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 70, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.buttonAgregar = QtWidgets.QPushButton(Dialog, clicked= lambda: self.agregar(nombre, self.oportunidad.text(),  self.contacto.text(),  self.ingresoEsperado.text(),  self.correo.text(),  self.telefono.text(),  self.tipo.text()))
        self.buttonAgregar.setGeometry(QtCore.QRect(160, 330, 75, 23))
        self.buttonAgregar.setObjectName("buttonAgregar")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(120, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Oportunidad"))
        self.label_2.setText(_translate("Dialog", "Contacto"))
        self.label_3.setText(_translate("Dialog", "Ingreso Esperado"))
        self.label_4.setText(_translate("Dialog", "Correo"))
        self.label_5.setText(_translate("Dialog", "Telefono"))
        self.label_6.setText(_translate("Dialog", "Tipo"))
        self.buttonAgregar.setText(_translate("Dialog", "Agregar"))
        self.label_7.setText(_translate("Dialog", "Nueva Oportunidad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
