
package paquete;
// Generated 5 feb 2024 13:20:42 by Hibernate Tools 6.3.1.Final

/**
 * Matricula generated by hbm2java
 */
public class Matricula implements java.io.Serializable {

	private MatriculaId id;
	private Ciclo ciclo;
	private Alumno alumno;
	private Modulo modulo;

	public Matricula() {
	}

	public Matricula(MatriculaId id, Ciclo ciclo, Alumno alumno, Modulo modulo) {
		this.id = id;
		this.ciclo = ciclo;
		this.alumno = alumno;
		this.modulo = modulo;
	}

	public MatriculaId getId() {
		return this.id;
	}

	public void setId(MatriculaId id) {
		this.id = id;
	}

	public Ciclo getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(Ciclo ciclo) {
		this.ciclo = ciclo;
	}

	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

}
