package paquete;
// Generated 5 feb 2024 13:20:42 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo implements java.io.Serializable {

	private String nombreCorto;
	private Profesor profesor;
	private Ciclo ciclo;
	private String nombre;
	private Integer horasSemanales;
	private Set notas = new HashSet(0);
	private Set matriculas = new HashSet(0);

	public Modulo() {
	}

	public Modulo(String nombreCorto, Profesor profesor, Ciclo ciclo, String nombre, Integer horasSemanales, Set notas,
			Set matriculas) {
		this.nombreCorto = nombreCorto;
		this.profesor = profesor;
		this.ciclo = ciclo;
		this.nombre = nombre;
		this.horasSemanales = horasSemanales;
		this.notas = notas;
		this.matriculas = matriculas;
	}

	public String getNombreCorto() {
		return this.nombreCorto;
	}

	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public Ciclo getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(Ciclo ciclo) {
		this.ciclo = ciclo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getHorasSemanales() {
		return this.horasSemanales;
	}

	public void setHorasSemanales(Integer horasSemanales) {
		this.horasSemanales = horasSemanales;
	}

	public Set getNotas() {
		return this.notas;
	}

	public void setNotas(Set notas) {
		this.notas = notas;
	}

	public Set getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set matriculas) {
		this.matriculas = matriculas;
	}

}
