
package paquete;
// Generated 5 feb 2024 13:20:42 by Hibernate Tools 6.3.1.Final

/**
 * NotaId generated by hbm2java
 */
public class NotaId implements java.io.Serializable {

	private int cursoAcademico;
	private String dniEstudiante;
	private int evaluacion;
	private String nombreCiclo;
	private String nombreModulo;
	private String tipoNota;

	public NotaId() {
	}

	public NotaId(int cursoAcademico, String dniEstudiante, int evaluacion, String nombreCiclo, String nombreModulo,
			String tipoNota) {
		this.cursoAcademico = cursoAcademico;
		this.dniEstudiante = dniEstudiante;
		this.evaluacion = evaluacion;
		this.nombreCiclo = nombreCiclo;
		this.nombreModulo = nombreModulo;
		this.tipoNota = tipoNota;
	}

	public int getCursoAcademico() {
		return this.cursoAcademico;
	}

	public void setCursoAcademico(int cursoAcademico) {
		this.cursoAcademico = cursoAcademico;
	}

	public String getDniEstudiante() {
		return this.dniEstudiante;
	}

	public void setDniEstudiante(String dniEstudiante) {
		this.dniEstudiante = dniEstudiante;
	}

	public int getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(int evaluacion) {
		this.evaluacion = evaluacion;
	}

	public String getNombreCiclo() {
		return this.nombreCiclo;
	}

	public void setNombreCiclo(String nombreCiclo) {
		this.nombreCiclo = nombreCiclo;
	}

	public String getNombreModulo() {
		return this.nombreModulo;
	}

	public void setNombreModulo(String nombreModulo) {
		this.nombreModulo = nombreModulo;
	}

	public String getTipoNota() {
		return this.tipoNota;
	}

	public void setTipoNota(String tipoNota) {
		this.tipoNota = tipoNota;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotaId))
			return false;
		NotaId castOther = (NotaId) other;

		return (this.getCursoAcademico() == castOther.getCursoAcademico())
				&& ((this.getDniEstudiante() == castOther.getDniEstudiante())
						|| (this.getDniEstudiante() != null && castOther.getDniEstudiante() != null
								&& this.getDniEstudiante().equals(castOther.getDniEstudiante())))
				&& (this.getEvaluacion() == castOther.getEvaluacion())
				&& ((this.getNombreCiclo() == castOther.getNombreCiclo())
						|| (this.getNombreCiclo() != null && castOther.getNombreCiclo() != null
								&& this.getNombreCiclo().equals(castOther.getNombreCiclo())))
				&& ((this.getNombreModulo() == castOther.getNombreModulo())
						|| (this.getNombreModulo() != null && castOther.getNombreModulo() != null
								&& this.getNombreModulo().equals(castOther.getNombreModulo())))
				&& ((this.getTipoNota() == castOther.getTipoNota()) || (this.getTipoNota() != null
						&& castOther.getTipoNota() != null && this.getTipoNota().equals(castOther.getTipoNota())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCursoAcademico();
		result = 37 * result + (getDniEstudiante() == null ? 0 : this.getDniEstudiante().hashCode());
		result = 37 * result + this.getEvaluacion();
		result = 37 * result + (getNombreCiclo() == null ? 0 : this.getNombreCiclo().hashCode());
		result = 37 * result + (getNombreModulo() == null ? 0 : this.getNombreModulo().hashCode());
		result = 37 * result + (getTipoNota() == null ? 0 : this.getTipoNota().hashCode());
		return result;
	}

}
