package paquete;
// Generated 5 feb 2024 13:20:42 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private String dni;
	private String nombre;
	private String apellidos;
	private String especialidad;
	private Set modulos = new HashSet(0);

	public Profesor() {
	}

	public Profesor(String dni, String nombre, String apellidos, String especialidad, Set modulos) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.especialidad = especialidad;
		this.modulos = modulos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public Set getModulos() {
		return this.modulos;
	}

	public void setModulos(Set modulos) {
		this.modulos = modulos;
	}

}
